kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s: 
      volumeClaimTemplate:
        spec:
          storageClassName: odf-lvm-vg1
          volumeMode: Filesystem
          resources:
            requests:
              storage: 10Gi
