kind: ConfigMap
apiVersion: v1
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
  uid: af22ad0a-7dfa-4fa0-b0c9-d33a217a1d56
  resourceVersion: '55149859'
  creationTimestamp: '2022-12-08T04:55:54Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-12-08T04:55:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:config.yaml': {}
data:
  config.yaml: |
    prometheus:
      volumeClaimTemplate:
        spec:
          storageClassName: odf-lvm-vg1
          resources:
            requests:
              storage: 10Gi
      retention: 24h
      resources:
        requests:
          cpu: 200m
          memory: 2Gi
