kind: ConfigMap
apiVersion: v1
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      volumeClaimTemplate:
        spec:
          storageClassName: odf-lvm-vg1
          resources:
            requests:
              storage: 10Gi
      retention: 24h
      resources:
        requests:
          cpu: 200m
          memory: 2Gi
