---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfgmap-mc2
  namespace: minecraft-wyatt
data:
  EULA: "TRUE"
  DIFFICULTY: normal
  LEVEL_TYPE: flat
  ONLINE_MODE: "false"
  DEFAULT_PLAYER_PERMISSION_LEVEL: "operator"
  MEMORY: 8G
  GAMEMODE: "creative"
  MAX_PLAYERS: "5"
  PVP: "false"
  MOTD: A Bedrock Minecraft Server for Wyatt
  PLAYER_IDLE_TIMEOUT: "0"
  OPS: 1264a1a5-8ac1-4d89-b9ad-064bebd66be4 
---
apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock
spec:
  type: NodePort
  ports:
  - port: 19132
    protocol: UDP
    nodePort: 30004
  selector:
    app: mc-bedrock
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mc-data-wyatt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-bedrock
spec:
  selector:
    matchLabels:
      app: mc-bedrock
  template:
    metadata:
      labels:
        app: mc-bedrock
    spec:
      containers:
      - image: docker.io/itzg/minecraft-bedrock-server
        name: mc-bedrock
        envFrom:
        - configMapRef:
            name: cfgmap-mc2
        volumeMounts:
          - mountPath: /data
            name: data
        ports:
        - containerPort: 19132
          name: main
          protocol: UDP
        readinessProbe: &probe
          exec:
            command:
              - mc-monitor
              - status-bedrock
              - --host
              # force health check against IPv4 port
              - 127.0.0.1
          initialDelaySeconds: 30
        livenessProbe: *probe
        tty: true
        stdin: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mc-data-wyatt
